org: craftsbot
app: craftsbot-template
service: craftsbot-template

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  exclude:
    - "**/*.ts"
    - "test/**"
    - "scripts/**"
    - ".vscode/**"
    - "*"

functions:
  http:
    handler: src/handle.handle
    timeout: 2
    events:
      - http: ANY /
      - http: ANY /{proxy+}
plugins:
  - serverless-offline
